import type { XrayReport } from "./types.js";

/**
 * The report as GitHub-flavoured Markdown.
 *
 * This is what a CI job summary or a PR comment wants: no ANSI, no box drawing,
 * short enough to read without scrolling. The HTML report stays the place to go
 * digging.
 */

export interface MarkdownOptions {
  /** Rows per table. Default 10. */
  top?: number;
  /** Prefix every heading with this level. Default 2 (`##`). */
  headingLevel?: number;
  /** Link file paths at this base, e.g. `https://github.com/o/r/blob/main/`. */
  blobBase?: string;
}

export function renderMarkdown(report: XrayReport, options: MarkdownOptions = {}): string {
  const top = options.top ?? 10;
  const h = "#".repeat(Math.min(5, Math.max(1, options.headingLevel ?? 2)));
  const out: string[] = [];

  const link = (path: string) => {
    const label = `\`${path}\``;
    if (!options.blobBase) return label;
    const base = options.blobBase.endsWith("/") ? options.blobBase : `${options.blobBase}/`;
    return `[${label}](${base}${path.split("/").map(encodeURIComponent).join("/")})`;
  };

  out.push(`${h} 🔬 crimescene`);
  out.push("");
  out.push(
    `**${report.repo}** — ${n(report.history.commits)} commits by ${n(report.history.authors)} authors, ` +
      `${report.history.from.slice(0, 10)} → ${report.history.to.slice(0, 10)}` +
      (report.history.since ? ` (since ${report.history.since})` : ""),
  );
  out.push("");

  if (report.files.length === 0) {
    out.push("No files scored. Try a wider `--since`, `--min-commits 1`, or `--include-all`.");
    out.push("");
    return out.join("\n");
  }

  const concentration = Math.round(report.totals.knowledgeConcentration * 100);
  const soloOwned = report.files.filter((file) => file.mainAuthorShare >= 0.8).length;
  out.push(
    `| Files | Top hotspot | Knowledge concentration | Single-owner files | Coupled pairs |`,
  );
  out.push(`|---:|---:|---:|---:|---:|`);
  out.push(
    `| ${n(report.totals.files)} | ${report.files[0]!.hotspot.toFixed(1)} | ${concentration}% | ` +
      `${n(soloOwned)} | ${n(report.coupling.length)} |`,
  );
  out.push("");

  out.push(`${h}# 🔥 Hotspots`);
  out.push("");
  out.push("Files that change often *and* are hard to read. Refactor from the top.");
  out.push("");
  out.push("| Score | File | Commits | LOC | Authors | Last touched |");
  out.push("|---:|:---|---:|---:|---:|---:|");
  for (const file of report.files.slice(0, top)) {
    out.push(
      `| ${file.hotspot.toFixed(1)} | ${link(file.path)} | ${n(file.commits)} | ${n(file.code)} | ` +
        `${n(file.authorCount)} | ${file.ageDays}d ago |`,
    );
  }
  out.push("");

  const atRisk = report.files.filter((file) => file.mainAuthorShare >= 0.8).slice(0, top);
  if (atRisk.length > 0) {
    out.push(`${h}# 🚌 Knowledge risk`);
    out.push("");
    out.push(`One person holds **${concentration}%** of the risky code.`);
    out.push("");
    out.push("| Owned | Author | File | Hotspot |");
    out.push("|---:|:---|:---|---:|");
    for (const file of atRisk) {
      out.push(
        `| ${Math.round(file.mainAuthorShare * 100)}% | ${escapeCell(file.mainAuthor)} | ` +
          `${link(file.path)} | ${file.hotspot.toFixed(1)} |`,
      );
    }
    out.push("");
  }

  if (report.coupling.length > 0) {
    out.push(`${h}# 🔗 Change coupling`);
    out.push("");
    out.push("Edited together, but stored apart.");
    out.push("");
    out.push("| Bond | File | Changes with | Shared commits |");
    out.push("|---:|:---|:---|---:|");
    for (const pair of report.coupling.slice(0, top)) {
      out.push(
        `| ${Math.round(pair.degree * 100)}% | ${link(pair.a)} | ${link(pair.b)} | ${n(pair.shared)} |`,
      );
    }
    out.push("");
  }

  if (report.warnings.length > 0) {
    out.push("<details><summary>Notes</summary>");
    out.push("");
    for (const warning of report.warnings) out.push(`- ${escapeCell(warning)}`);
    out.push("");
    out.push("</details>");
    out.push("");
  }

  out.push(
    `<sub>Generated by [crimescene](https://github.com/JamesJoe716/crimescene) v${report.tool.version}. ` +
      `Hotspot = √(change frequency × complexity).</sub>`,
  );
  out.push("");
  return out.join("\n");
}

function n(value: number): string {
  return value.toLocaleString("en-US");
}

/** A literal `|` would split the row into an extra column. */
function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}
