import { RAMP_DARK, RAMP_LIGHT, SHARED_SOURCE } from "./treemap.js";
import type { XrayReport } from "./types.js";

/**
 * Renders the analysis as a single self-contained HTML file: no CDN, no fonts,
 * no fetch. It has to open from `file://` on a locked-down laptop, so every
 * byte it needs is inlined here.
 *
 * Colour follows a sequential encoding — one hue, monotone lightness — stepped
 * separately for each surface rather than flipped. On the dark surface the ramp
 * runs the other way so "near zero" always recedes toward the background.
 *
 * The layout maths is not duplicated here: `SHARED_SOURCE` is the literal
 * source of the functions in `treemap.ts`, so the browser and the `--svg`
 * renderer run the same code rather than two copies that drift.
 */

export function renderReport(report: XrayReport): string {
  // The payload sits in an `application/json` block read via textContent, so the
  // only sequence that could break out of it is `</script>`. Escaping `<` is
  // enough, and JSON.parse decodes the escape on the way back in.
  const payload = JSON.stringify(report).replace(/</g, "\\u003c");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="crimescene ${escapeHtml(report.tool.version)}">
<title>${escapeHtml(report.repo)} — crimescene report</title>
<style>${STYLE}</style>
</head>
<body>
<div class="wrap">
  <header class="head">
    <div>
      <h1>${escapeHtml(report.repo)}</h1>
      <p class="sub" id="sub"></p>
    </div>
    <button id="theme" class="ghost" type="button" aria-label="Toggle colour theme">Theme</button>
  </header>

  <section class="tiles" id="tiles" aria-label="Summary"></section>

  <section class="panel">
    <div class="panel-head">
      <div>
        <h2>Hotspot map</h2>
        <p class="hint">Area = lines of code &nbsp;·&nbsp; colour = hotspot score &nbsp;·&nbsp; click a folder to zoom in</p>
      </div>
      <nav class="crumbs" id="crumbs" aria-label="Breadcrumb"></nav>
    </div>
    <div class="mapwrap">
      <svg id="map" viewBox="0 0 1000 580" preserveAspectRatio="xMidYMid meet" role="img"
           aria-label="Treemap of the repository, sized by lines of code and coloured by hotspot score"></svg>
      <div id="tip" class="tip" role="tooltip" aria-hidden="true"></div>
    </div>
    <div class="legend" aria-hidden="true">
      <span class="legend-label">cold</span>
      <span class="legend-bar" id="legendbar"></span>
      <span class="legend-label">hot</span>
    </div>
  </section>

  <section class="panel">
    <div class="tabs" role="tablist">
      <button class="tab is-on" role="tab" data-tab="hotspots" type="button">Hotspots</button>
      <button class="tab" role="tab" data-tab="knowledge" type="button">Knowledge risk</button>
      <button class="tab" role="tab" data-tab="coupling" type="button">Coupling</button>
      <button class="tab" role="tab" data-tab="authors" type="button">Authors</button>
      <input id="q" class="search" type="search" placeholder="Filter by path or name…" aria-label="Filter rows">
    </div>
    <p class="hint" id="tabhint"></p>
    <div class="tablewrap"><table id="table"><thead></thead><tbody></tbody></table></div>
    <p class="empty" id="empty" hidden>Nothing matches that filter.</p>
  </section>

  <section class="panel notes" id="notes"></section>

  <footer class="foot">
    Generated by <strong>crimescene</strong> v${escapeHtml(report.tool.version)} ·
    <span id="stamp"></span> · analysis runs entirely offline
  </footer>
</div>
<script id="data" type="application/json">${payload}</script>
<script>${SCRIPT.replace("__RAMP_LIGHT__", JSON.stringify(RAMP_LIGHT))
    .replace("__RAMP_DARK__", JSON.stringify(RAMP_DARK))
    .replace("__SHARED__", () => SHARED_SOURCE)}</script>
</body>
</html>
`;
}

function escapeHtml(text: string): string {
  return text.replace(
    /[&<>"']/g,
    (char) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char] ?? char,
  );
}

const STYLE = `
:root {
  color-scheme: light;
  --surface-0: #f9f9f7;
  --surface-1: #fcfcfb;
  --surface-2: #f2f1ed;
  --text-1: #0b0b0b;
  --text-2: #52514e;
  --muted:   #898781;
  --line:    #e1e0d9;
  --ring:    rgba(11,11,11,.10);
  --accent:  #2a78d6;
  --critical:#d03b3b;
  --warning: #fab219;
  --good:    #0ca30c;
  --ink-dark: #0b0b0b;
  --ink-light: #fcfcfb;
  --shadow: 0 1px 2px rgba(11,11,11,.05), 0 8px 24px rgba(11,11,11,.06);
}
@media (prefers-color-scheme: dark) {
  :root:where(:not([data-theme="light"])) {
    color-scheme: dark;
    --surface-0: #0d0d0d;
    --surface-1: #1a1a19;
    --surface-2: #222220;
    --text-1: #ffffff;
    --text-2: #c3c2b7;
    --muted:   #898781;
    --line:    #2c2c2a;
    --ring:    rgba(255,255,255,.10);
    --accent:  #3987e5;
    --critical:#d03b3b;
    --ink-dark: #1a1a19;
    --ink-light: #ffffff;
    --shadow: 0 1px 2px rgba(0,0,0,.4), 0 8px 24px rgba(0,0,0,.35);
  }
}
:root[data-theme="dark"] {
  color-scheme: dark;
  --surface-0: #0d0d0d;
  --surface-1: #1a1a19;
  --surface-2: #222220;
  --text-1: #ffffff;
  --text-2: #c3c2b7;
  --muted:   #898781;
  --line:    #2c2c2a;
  --ring:    rgba(255,255,255,.10);
  --accent:  #3987e5;
  --critical:#d03b3b;
  --ink-dark: #1a1a19;
  --ink-light: #ffffff;
  --shadow: 0 1px 2px rgba(0,0,0,.4), 0 8px 24px rgba(0,0,0,.35);
}

* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--surface-0);
  color: var(--text-1);
  font: 15px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif;
  -webkit-font-smoothing: antialiased;
}
.wrap { max-width: 1180px; margin: 0 auto; padding: 32px 20px 64px; }

.head { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; margin-bottom: 24px; }
h1 { margin: 0; font-size: 26px; letter-spacing: -.02em; }
h2 { margin: 0; font-size: 15px; letter-spacing: .01em; }
.sub { margin: 4px 0 0; color: var(--text-2); font-size: 13.5px; }
.hint { margin: 4px 0 0; color: var(--muted); font-size: 12.5px; }

.ghost {
  background: transparent; color: var(--text-2); border: 1px solid var(--line);
  border-radius: 8px; padding: 6px 12px; font: inherit; font-size: 13px; cursor: pointer;
}
.ghost:hover { background: var(--surface-2); color: var(--text-1); }

.tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 12px; margin-bottom: 20px; }
.tile {
  background: var(--surface-1); border: 1px solid var(--line); border-radius: 12px;
  padding: 14px 16px; box-shadow: var(--shadow);
}
.tile .k { font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: .06em; }
.tile .v { font-size: 27px; line-height: 1.2; margin-top: 4px; letter-spacing: -.02em; }
.tile .n { font-size: 12.5px; color: var(--text-2); margin-top: 2px; }
.tile.alert .v { color: var(--critical); }

.panel {
  background: var(--surface-1); border: 1px solid var(--line); border-radius: 14px;
  padding: 18px; margin-bottom: 20px; box-shadow: var(--shadow);
}
.panel-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; flex-wrap: wrap; margin-bottom: 14px; }

.crumbs { display: flex; align-items: center; flex-wrap: wrap; gap: 4px; font-size: 13px; }
.crumbs button {
  background: none; border: 0; padding: 3px 7px; border-radius: 6px;
  font: inherit; color: var(--accent); cursor: pointer;
}
.crumbs button:hover { background: var(--surface-2); }
.crumbs span { color: var(--muted); }
.crumbs .now { color: var(--text-2); padding: 3px 2px; }

.mapwrap { position: relative; }
#map { display: block; width: 100%; height: auto; border-radius: 10px; background: var(--surface-2); }
#map .cell { cursor: default; }
#map .cell.zoomable { cursor: pointer; }
#map rect { shape-rendering: crispEdges; }
#map .box { fill: var(--surface-1); stroke: var(--ring); stroke-width: 1; }
#map .band { fill: var(--surface-2); }
#map text { pointer-events: none; font-size: 11px; font-family: inherit; }
#map .dirname { fill: var(--text-2); font-size: 11px; font-weight: 600; }
#map .cell:hover > rect.heat { stroke: var(--text-1); stroke-width: 2; }

.tip {
  position: absolute; z-index: 5; pointer-events: none; opacity: 0;
  transition: opacity .1s ease; max-width: 340px;
  background: var(--surface-1); color: var(--text-1);
  border: 1px solid var(--line); border-radius: 10px; padding: 10px 12px;
  box-shadow: var(--shadow); font-size: 12.5px; line-height: 1.5;
}
.tip.on { opacity: 1; }
.tip .p { font-weight: 600; word-break: break-all; margin-bottom: 6px; }
.tip dl { display: grid; grid-template-columns: auto auto; gap: 2px 14px; margin: 0; }
.tip dt { color: var(--muted); }
.tip dd { margin: 0; text-align: right; font-variant-numeric: tabular-nums; }

.legend { display: flex; align-items: center; gap: 10px; margin-top: 12px; }
.legend-label { font-size: 12px; color: var(--muted); }
.legend-bar { flex: 1; height: 8px; border-radius: 4px; border: 1px solid var(--ring); }

.tabs { display: flex; align-items: center; gap: 6px; flex-wrap: wrap; margin-bottom: 4px; }
.tab {
  background: transparent; border: 1px solid transparent; border-radius: 8px;
  padding: 7px 12px; font: inherit; font-size: 13.5px; color: var(--text-2); cursor: pointer;
}
.tab:hover { background: var(--surface-2); color: var(--text-1); }
.tab.is-on { background: var(--surface-2); border-color: var(--line); color: var(--text-1); font-weight: 600; }
.search {
  margin-left: auto; min-width: 200px; background: var(--surface-0); color: var(--text-1);
  border: 1px solid var(--line); border-radius: 8px; padding: 7px 11px; font: inherit; font-size: 13.5px;
}
.search:focus { outline: 2px solid var(--accent); outline-offset: 1px; }

.tablewrap { overflow-x: auto; margin-top: 12px; }
table { width: 100%; border-collapse: collapse; font-size: 13.5px; }
th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--line); white-space: nowrap; }
th {
  position: sticky; top: 0; background: var(--surface-1); color: var(--muted);
  font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: .05em;
  cursor: pointer; user-select: none;
}
th:hover { color: var(--text-1); }
th.sorted::after { content: " ▾"; color: var(--accent); }
th.sorted.asc::after { content: " ▴"; }
td.num { text-align: right; font-variant-numeric: tabular-nums; }
td.path { white-space: normal; word-break: break-all; max-width: 460px; }
tbody tr:hover { background: var(--surface-2); }
.chip {
  display: inline-block; min-width: 42px; text-align: center; padding: 1px 7px;
  border-radius: 999px; font-variant-numeric: tabular-nums; font-size: 12.5px;
}
.risk { color: var(--critical); font-weight: 600; }
.dim { color: var(--muted); }
.empty { color: var(--muted); font-size: 13.5px; padding: 14px 2px 2px; }

.notes { font-size: 13px; color: var(--text-2); }
.notes h2 { margin-bottom: 8px; }
.notes ul { margin: 0; padding-left: 18px; }
.notes li { margin: 3px 0; }
.notes:empty { display: none; }
.foot { color: var(--muted); font-size: 12.5px; text-align: center; }

@media (max-width: 640px) {
  .wrap { padding: 20px 12px 48px; }
  .search { margin-left: 0; width: 100%; }
  td.path { max-width: 220px; }
}
`;

/**
 * Browser-side code. Deliberately written without template literals so that
 * embedding it in a TypeScript template literal cannot mangle it, and without
 * regex escapes for the same reason.
 */
const SCRIPT = `
"use strict";
(function () {
  var RAMP_LIGHT = __RAMP_LIGHT__;
  var RAMP_DARK  = __RAMP_DARK__;
  var DATA = JSON.parse(document.getElementById("data").textContent);

  /* The literal source of src/treemap.ts — buildTree, nodeHotspot, squarify,
     heatColor, inkOn and clipLabel — so this page and the --svg renderer share
     one implementation instead of two that drift. */
__SHARED__

  /* ---------- helpers ---------- */
  var num = function (n) { return (n == null ? 0 : n).toLocaleString(); };
  var pct = function (n) { return Math.round(n * 100) + "%"; };
  var el = function (tag, cls, text) {
    var node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text != null) node.textContent = String(text);
    return node;
  };
  var svgEl = function (tag) { return document.createElementNS("http://www.w3.org/2000/svg", tag); };
  var day = function (iso) { return iso ? String(iso).slice(0, 10) : "—"; };
  var base = function (path) { var i = path.lastIndexOf("/"); return i === -1 ? path : path.slice(i + 1); };

  var isDark = function () {
    var stamped = document.documentElement.getAttribute("data-theme");
    if (stamped) return stamped === "dark";
    return window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
  };
  var ramp = function () { return isDark() ? RAMP_DARK : RAMP_LIGHT; };

  /* Sample the current theme's ramp; t is 0..1. */
  var heat = function (t) { return heatColor(t, ramp()); };
  /* Pick the ink that survives on this fill. */
  var ink = function (color) {
    return inkOn(color) === "dark" ? "var(--ink-dark)" : "var(--ink-light)";
  };

  var maxHotspot = 0;
  for (var i = 0; i < DATA.files.length; i++) {
    if (DATA.files[i].hotspot > maxHotspot) maxHotspot = DATA.files[i].hotspot;
  }
  var scale = function (hotspot) { return maxHotspot > 0 ? hotspot / maxHotspot : 0; };

  /* ---------- header ---------- */
  document.getElementById("sub").textContent =
    num(DATA.history.commits) + " commits by " + num(DATA.history.authors) + " authors  ·  " +
    day(DATA.history.from) + " → " + day(DATA.history.to) +
    (DATA.history.since ? "  ·  since " + DATA.history.since : "");
  document.getElementById("stamp").textContent = day(DATA.generatedAt);

  var topFile = DATA.files[0];
  var soloOwned = DATA.files.filter(function (f) { return f.mainAuthorShare >= 0.8; });
  var tiles = [
    { k: "Files analysed", v: num(DATA.totals.files), n: num(DATA.totals.code) + " lines of code" },
    { k: "Top hotspot", v: topFile ? topFile.hotspot.toFixed(0) : "—",
      n: topFile ? base(topFile.path) : "nothing scored" },
    { k: "Knowledge concentration", v: pct(DATA.totals.knowledgeConcentration),
      n: "held by one person", alert: DATA.totals.knowledgeConcentration >= 0.5 },
    { k: "Single-owner files", v: num(soloOwned.length),
      n: "one author wrote 80%+", alert: DATA.totals.files > 0 && soloOwned.length / DATA.totals.files >= 0.4 },
    { k: "Coupled pairs", v: num(DATA.coupling.length), n: "change together, live apart" }
  ];
  var tileBox = document.getElementById("tiles");
  tiles.forEach(function (t) {
    var card = el("div", "tile" + (t.alert ? " alert" : ""));
    card.appendChild(el("div", "k", t.k));
    card.appendChild(el("div", "v", t.v));
    card.appendChild(el("div", "n", t.n));
    tileBox.appendChild(card);
  });

  /* ---------- hierarchy ---------- */
  /* buildTree, nodeHotspot and squarify come from the shared block above. */
  var TREE = buildTree(DATA.files, DATA.repo);

  /* ---------- map rendering ---------- */
  var MAP_W = 1000, MAP_H = 580, GAP = 2, BAND = 15, MAX_DEPTH = 3;
  var svg = document.getElementById("map");
  var tip = document.getElementById("tip");
  var crumbs = document.getElementById("crumbs");
  var focusPath = "";

  function findNode(path) {
    if (!path) return TREE;
    var parts = path.split("/"), node = TREE;
    for (var i = 0; i < parts.length; i++) {
      var next = null;
      for (var j = 0; j < node.children.length; j++) {
        if (node.children[j].name === parts[i] && node.children[j].children) { next = node.children[j]; break; }
      }
      if (!next) return node;
      node = next;
    }
    return node;
  }

  function showTip(event, node) {
    var file = node.file;
    var rows = file
      ? [["Hotspot", file.hotspot.toFixed(1)], ["Commits", num(file.commits)],
         ["Lines of code", num(file.code)], ["Complexity", num(file.complexity)],
         ["Authors", num(file.authorCount)], ["Main author", file.mainAuthor + " (" + pct(file.mainAuthorShare) + ")"],
         ["Bus factor", String(file.busFactor)], ["Last change", day(file.lastChange)]]
      : [["Files", num(node.files)], ["Lines of code", num(node.value)],
         ["Mean hotspot", nodeHotspot(node).toFixed(1)], ["", "click to zoom in"]];
    tip.textContent = "";
    tip.appendChild(el("div", "p", file ? file.path : node.path || DATA.repo));
    var dl = el("dl");
    rows.forEach(function (row) {
      dl.appendChild(el("dt", null, row[0]));
      dl.appendChild(el("dd", null, row[1]));
    });
    tip.appendChild(dl);
    tip.classList.add("on");
    tip.setAttribute("aria-hidden", "false");
    moveTip(event);
  }
  function moveTip(event) {
    var box = svg.parentElement.getBoundingClientRect();
    var x = event.clientX - box.left + 14;
    var y = event.clientY - box.top + 14;
    if (x + tip.offsetWidth > box.width) x = Math.max(0, event.clientX - box.left - tip.offsetWidth - 14);
    if (y + tip.offsetHeight > box.height) y = Math.max(0, event.clientY - box.top - tip.offsetHeight - 14);
    tip.style.left = x + "px";
    tip.style.top = y + "px";
  }
  function hideTip() {
    tip.classList.remove("on");
    tip.setAttribute("aria-hidden", "true");
  }

  function draw() {
    svg.textContent = "";
    var root = findNode(focusPath);
    paint(root, { x: 1, y: 1, w: MAP_W - 2, h: MAP_H - 2 }, 0);
    renderCrumbs(root);
  }

  function paint(node, rect, depth) {
    var expandable = node.children && node.children.length > 0;
    var canExpand = expandable && depth < MAX_DEPTH && rect.w > 42 && rect.h > 42;

    if (!canExpand) {
      leaf(node, rect, expandable);
      return;
    }
    // The outermost container is the map itself: it has nowhere to zoom to, and
    // marking it zoomable would put an inert click target over the whole chart.
    var isRoot = depth === 0;
    var group = svgEl("g");
    group.setAttribute("class", isRoot ? "cell" : "cell zoomable");
    var box = svgEl("rect");
    box.setAttribute("class", "box");
    box.setAttribute("x", rect.x); box.setAttribute("y", rect.y);
    box.setAttribute("width", rect.w); box.setAttribute("height", rect.h);
    box.setAttribute("rx", "3");
    group.appendChild(box);

    var band = 0;
    if (depth > 0 && rect.h > BAND * 2.4 && rect.w > 60) {
      band = BAND;
      var strip = svgEl("rect");
      strip.setAttribute("class", "band");
      strip.setAttribute("x", rect.x + 1); strip.setAttribute("y", rect.y + 1);
      strip.setAttribute("width", rect.w - 2); strip.setAttribute("height", band);
      group.appendChild(strip);
      var label = svgEl("text");
      label.setAttribute("class", "dirname");
      label.setAttribute("x", rect.x + 6);
      label.setAttribute("y", rect.y + band - 4);
      label.textContent = clipLabel(node.name, rect.w - 12);
      group.appendChild(label);
    }
    if (!isRoot) {
      group.addEventListener("mouseenter", function (e) { showTip(e, node); });
      group.addEventListener("mousemove", moveTip);
      group.addEventListener("mouseleave", hideTip);
      group.addEventListener("click", function (e) { e.stopPropagation(); zoom(node.path); });
    }
    svg.appendChild(group);

    var inner = {
      x: rect.x + GAP, y: rect.y + band + GAP,
      w: rect.w - GAP * 2, h: rect.h - band - GAP * 2
    };
    squarify(node.children, inner).forEach(function (cell) {
      paint(cell.node, { x: cell.x + GAP / 2, y: cell.y + GAP / 2, w: cell.w - GAP, h: cell.h - GAP }, depth + 1);
    });
  }

  function leaf(node, rect, isFolder) {
    if (rect.w <= 0.5 || rect.h <= 0.5) return;
    var score = node.file ? node.file.hotspot : nodeHotspot(node);
    var fill = heat(scale(score));
    var group = svgEl("g");
    group.setAttribute("class", "cell" + (isFolder ? " zoomable" : ""));

    var box = svgEl("rect");
    box.setAttribute("class", "heat");
    box.setAttribute("x", rect.x); box.setAttribute("y", rect.y);
    box.setAttribute("width", rect.w); box.setAttribute("height", rect.h);
    box.setAttribute("rx", rect.w > 8 && rect.h > 8 ? "3" : "0");
    box.setAttribute("fill", fill);
    box.setAttribute("stroke", "var(--ring)");
    group.appendChild(box);

    if (rect.w > 54 && rect.h > 18) {
      var text = svgEl("text");
      text.setAttribute("x", rect.x + 5);
      text.setAttribute("y", rect.y + 13);
      text.setAttribute("fill", ink(fill));
      text.textContent = clipLabel(isFolder ? node.name + "/" : node.name, rect.w - 10);
      group.appendChild(text);
    }
    group.addEventListener("mouseenter", function (e) { showTip(e, node); });
    group.addEventListener("mousemove", moveTip);
    group.addEventListener("mouseleave", hideTip);
    if (isFolder) {
      group.addEventListener("click", function (e) { e.stopPropagation(); zoom(node.path); });
    }
    svg.appendChild(group);
  }

  function zoom(path) {
    if (!path || path === focusPath) return;
    focusPath = path;
    hideTip();
    draw();
  }

  function renderCrumbs(root) {
    crumbs.textContent = "";
    var trail = [{ name: DATA.repo, path: "" }];
    if (focusPath) {
      focusPath.split("/").forEach(function (part, i, all) {
        trail.push({ name: part, path: all.slice(0, i + 1).join("/") });
      });
    }
    trail.forEach(function (step, i) {
      if (i > 0) crumbs.appendChild(el("span", null, "/"));
      if (i === trail.length - 1) {
        crumbs.appendChild(el("span", "now", step.name));
      } else {
        var button = el("button", null, step.name);
        button.type = "button";
        button.addEventListener("click", function () { focusPath = step.path; hideTip(); draw(); });
        crumbs.appendChild(button);
      }
    });
    if (root.children && root.children.length === 0) {
      crumbs.appendChild(el("span", "now", " (empty)"));
    }
  }

  function paintLegend() {
    var stops = ramp().join(", ");
    document.getElementById("legendbar").style.background = "linear-gradient(to right, " + stops + ")";
  }

  /* ---------- tables ---------- */
  var VIEWS = {
    hotspots: {
      hint: "Files that change often and are hard to read. Start refactoring at the top.",
      columns: [
        { k: "hotspot", label: "Score", num: true, render: function (r) { return chip(r.hotspot); } },
        { k: "path", label: "File", path: true },
        { k: "commits", label: "Commits", num: true },
        { k: "code", label: "LOC", num: true },
        { k: "complexity", label: "Complexity", num: true },
        { k: "maxIndent", label: "Max depth", num: true },
        { k: "authorCount", label: "Authors", num: true },
        { k: "ageDays", label: "Last touched", num: true, render: function (r) { return r.ageDays + "d ago"; } }
      ],
      rows: function () { return DATA.files.slice(0, 300); },
      sort: "hotspot"
    },
    knowledge: {
      hint: "Files with a dominant author. A high share plus a high hotspot score is where a departure hurts.",
      columns: [
        { k: "mainAuthorShare", label: "Owned", num: true,
          render: function (r) {
            var span = el("span", r.mainAuthorShare >= 0.8 ? "risk" : null, pct(r.mainAuthorShare));
            return span;
          } },
        { k: "mainAuthor", label: "Main author" },
        { k: "path", label: "File", path: true },
        { k: "busFactor", label: "Bus factor", num: true },
        { k: "authorCount", label: "Authors", num: true },
        { k: "hotspot", label: "Hotspot", num: true, render: function (r) { return chip(r.hotspot); } },
        { k: "ageDays", label: "Last touched", num: true, render: function (r) { return r.ageDays + "d ago"; } }
      ],
      rows: function () {
        return DATA.files.filter(function (f) { return f.mainAuthorShare >= 0.5; })
          .sort(function (a, b) { return b.hotspot * b.mainAuthorShare - a.hotspot * a.mainAuthorShare; })
          .slice(0, 300);
      },
      sort: null
    },
    coupling: {
      hint: "Files that keep changing in the same commit. Invisible in the folder tree, expensive when missed.",
      columns: [
        { k: "degree", label: "Coupling", num: true, render: function (r) { return pct(r.degree); } },
        { k: "a", label: "File", path: true },
        { k: "b", label: "Changes with", path: true },
        { k: "shared", label: "Shared commits", num: true },
        { k: "aCommits", label: "Commits (A)", num: true },
        { k: "bCommits", label: "Commits (B)", num: true }
      ],
      rows: function () { return DATA.coupling; },
      sort: null
    },
    authors: {
      hint: "Who has been where. 'Owns' counts files where this author wrote the largest share.",
      columns: [
        { k: "author", label: "Author" },
        { k: "commits", label: "Commits", num: true },
        { k: "files", label: "Files touched", num: true },
        { k: "owned", label: "Owns", num: true },
        { k: "added", label: "Lines +", num: true },
        { k: "deleted", label: "Lines −", num: true },
        { k: "lastCommit", label: "Last commit", render: function (r) { return day(r.lastCommit); } }
      ],
      rows: function () { return DATA.authors; },
      sort: null
    }
  };

  function chip(score) {
    var span = el("span", "chip", score.toFixed(1));
    var fill = heat(scale(score));
    span.style.background = fill;
    span.style.color = ink(fill);
    return span;
  }

  var current = "hotspots";
  var sortKey = "hotspot";
  var sortAsc = false;
  var table = document.getElementById("table");
  var query = document.getElementById("q");
  var emptyNote = document.getElementById("empty");

  function renderTable() {
    var view = VIEWS[current];
    document.getElementById("tabhint").textContent = view.hint;

    var rows = view.rows().slice();
    var needle = query.value.trim().toLowerCase();
    if (needle) {
      rows = rows.filter(function (row) {
        var hay = (row.path || "") + " " + (row.a || "") + " " + (row.b || "") + " " +
                  (row.author || "") + " " + (row.mainAuthor || "");
        return hay.toLowerCase().indexOf(needle) !== -1;
      });
    }
    if (sortKey) {
      rows.sort(function (x, y) {
        var a = x[sortKey], b = y[sortKey];
        if (typeof a === "number" && typeof b === "number") return sortAsc ? a - b : b - a;
        a = String(a); b = String(b);
        return sortAsc ? a.localeCompare(b) : b.localeCompare(a);
      });
    }

    var head = table.tHead, body = table.tBodies[0];
    head.textContent = ""; body.textContent = "";
    var tr = el("tr");
    view.columns.forEach(function (col) {
      var th = el("th", null, col.label);
      if (col.num) th.className = "num";
      if (col.k === sortKey) th.className = (th.className + " sorted " + (sortAsc ? "asc" : "")).trim();
      th.addEventListener("click", function () {
        if (sortKey === col.k) sortAsc = !sortAsc;
        else { sortKey = col.k; sortAsc = false; }
        renderTable();
      });
      tr.appendChild(th);
    });
    head.appendChild(tr);

    rows.slice(0, 300).forEach(function (row) {
      var line = el("tr");
      view.columns.forEach(function (col) {
        var cell = el("td");
        if (col.num) cell.className = "num";
        if (col.path) cell.className = "path";
        var value = col.render ? col.render(row) : row[col.k];
        if (value && value.nodeType) cell.appendChild(value);
        else cell.textContent = typeof value === "number" ? num(value) : String(value == null ? "—" : value);
        line.appendChild(cell);
      });
      body.appendChild(line);
    });

    emptyNote.hidden = rows.length > 0;
  }

  Array.prototype.forEach.call(document.querySelectorAll(".tab"), function (button) {
    button.addEventListener("click", function () {
      Array.prototype.forEach.call(document.querySelectorAll(".tab"), function (other) {
        other.classList.toggle("is-on", other === button);
      });
      current = button.getAttribute("data-tab");
      sortKey = VIEWS[current].sort;
      sortAsc = false;
      renderTable();
    });
  });
  query.addEventListener("input", renderTable);

  /* ---------- notes ---------- */
  var notes = document.getElementById("notes");
  var items = DATA.warnings.slice();
  items.push("Complexity is measured by indentation depth, a language-agnostic proxy — it ranks files, it does not audit them.");
  items.push("Hotspot score is the geometric mean of change frequency and complexity, each normalised against the busiest file in range.");
  if (items.length) {
    notes.appendChild(el("h2", null, "Reading this report"));
    var list = el("ul");
    items.forEach(function (text) { list.appendChild(el("li", null, text)); });
    notes.appendChild(list);
  }

  /* ---------- theme ---------- */
  document.getElementById("theme").addEventListener("click", function () {
    document.documentElement.setAttribute("data-theme", isDark() ? "light" : "dark");
    paintLegend();
    draw();
    renderTable();
  });
  if (window.matchMedia) {
    window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", function () {
      if (!document.documentElement.getAttribute("data-theme")) { paintLegend(); draw(); renderTable(); }
    });
  }

  paintLegend();
  draw();
  renderTable();
})();
`;
